#!/bin/sh
#
# @name Gazebo swan_gamma_v2
#
# @type Quadrotor
#

PX4_SIMULATOR=${PX4_SIMULATOR:=gz}
PX4_GZ_WORLD=${PX4_GZ_WORLD:=laboratory_no_landingbox}
PX4_SIM_MODEL=${PX4_SIM_MODEL:=swan_gamma_v2}
PX4_GZ_MODEL_POSE=${PX4_GZ_MODEL_POSE:="0,0,1.15392,0,0,0"}

. ${R}etc/init.d/rc.mc_defaults

param set-default MAV_TYPE 2

# Disable power check for simulation
param set-default CBRK_SUPPLY_CHK 894281

# Control allocation: Quad X
param set-default CA_AIRFRAME 0
param set-default CA_ROTOR_COUNT 4

# CA_ROTOR to SDF motorNumber mapping:
# CA_ROTOR0 → motorNumber 0 (FL, cw) → KM=-0.06
# CA_ROTOR1 → motorNumber 1 (BR, cw) → KM=-0.06
# CA_ROTOR2 → motorNumber 2 (FR, ccw) → KM=+0.06
# CA_ROTOR3 → motorNumber 3 (BL, ccw) → KM=+0.06
param set-default CA_ROTOR0_PX 0.29
param set-default CA_ROTOR0_PY -0.347
param set-default CA_ROTOR0_KM -0.06

param set-default CA_ROTOR1_PX -0.31
param set-default CA_ROTOR1_PY 0.337
param set-default CA_ROTOR1_KM -0.06

param set-default CA_ROTOR2_PX 0.29
param set-default CA_ROTOR2_PY 0.347
param set-default CA_ROTOR2_KM 0.06

param set-default CA_ROTOR3_PX -0.31
param set-default CA_ROTOR3_PY -0.337
param set-default CA_ROTOR3_KM 0.06

# Gazebo ESC output mapping
param set-default SIM_GZ_EN 1
param set-default EKF2_SENS_EN 8191

# No external-vision source is used in this simulation. Gazebo/PX4 provide the
# odometry consumed by SUPER through gz_sensor_interface.
param set-default EKF2_EV_CTRL 0

param set-default SIM_GZ_EC_FUNC1 101
param set-default SIM_GZ_EC_FUNC2 102
param set-default SIM_GZ_EC_FUNC3 103
param set-default SIM_GZ_EC_FUNC4 104

param set-default SIM_GZ_EC_MIN1 150
param set-default SIM_GZ_EC_MIN2 150
param set-default SIM_GZ_EC_MIN3 150
param set-default SIM_GZ_EC_MIN4 150

param set-default SIM_GZ_EC_MAX1 1000
param set-default SIM_GZ_EC_MAX2 1000
param set-default SIM_GZ_EC_MAX3 1000
param set-default SIM_GZ_EC_MAX4 1000

param set-default MPC_THR_HOVER 0.8

param set-default USR_LAMBDA_Q_X 12.00
param set-default USR_LAMBDA_Q_Y 14.50
param set-default USR_LAMBDA_Q_Z 12.00
param set-default USR_I_YY 0.40
param set-default USR_I_ZZ 0.40
param set-default USR_YAWRATE_MAX 40.0

# Allow arming without QGroundControl / RC.
param set-default COM_RCL_EXCEPT 7
param set-default NAV_RCL_ACT 0
param set-default NAV_DLL_ACT 0
param set-default COM_ARM_WO_GPS 1
param set-default SIM_BAT_ENABLE 0

param set-default MC_ROLLRATE_K 1.2
param set-default MC_ROLLRATE_D 0.003
param set-default MC_ROLLRATE_I 0.35
param set-default MC_PITCHRATE_K 1.58
param set-default MC_PITCHRATE_D 0.004
param set-default MC_PITCHRATE_I 0.35
param set-default MC_YAWRATE_K 3.0

param set-default MC_ROLL_P 4.5
param set-default MC_PITCH_P 6.0
param set-default MC_YAW_P 2.0

param set-default MPC_XY_VEL_P_ACC 2.0
param set-default MPC_XY_VEL_D_ACC 0.3
